services:

  frontend:
    build: ./audio-room-client
    expose:
      - "80"
    mem_limit: 64m
    ulimits:
      nproc: 1024
      nofile: 4096

  websocket:
    build: ./ws
    container_name: websocket
    environment:
      WS_PORT: 3000
    expose:
      - "3000"
    restart: unless-stopped 
    mem_limit: 64m
    ulimits:
      nofile: 4096


  janus:
    build:
      context: ./janus
      dockerfile: Dockerfile
      args:
        JANUS_VERSION: v1.3.1

    image: janus-gateway:local
    container_name: janus

    ports:
    # - "8088:8088" 
    # - "8089:8089"
    # - "8188:8188"
    # - "8189:8189"
     - "10000-10200:10000-10200/udp"
    # - "7088:7088"
    # - "7089:7089"
    environment:
      - JANUS_CERT_PEM=${LETSENCRYPT_PATH}/fullchain.pem
      - JANUS_CERT_KEY=${LETSENCRYPT_PATH}/privkey.pem

    restart: unless-stopped
    # Optional: mount your own janus.cfg if you have one
    volumes:
      - ${LETSENCRYPT_PATH}:${LETSENCRYPT_PATH}:ro
      - ./janus/janus.jcfg:/opt/janus/etc/janus/janus.jcfg
      - ./janus/janus.transport.http.jcfg:/opt/janus/etc/janus/janus.transport.http.jcfg
    mem_limit: 256m
    ulimits:
      nofile: 8192

  coturn:
    build: ./coturn
    environment:
      - TURN_USERDB=/etc/turnserver/turnuserdb.txt
      #- TURN_USER=demo
      #- TURN_PASS=demo
    volumes:
      - ./turn/turnserver.conf:/etc/turnserver/turnserver.conf:ro
      - ./turn/turnuserdb.txt:/etc/turnserver/turnuserdb.txt:ro
      - ${LETSENCRYPT_PATH}:/etc/letsencrypt/live/:ro 
    ports:
      - "3478:3478/tcp"
      - "3478:3478/udp"
      - "5349:5349/tcp"
    mem_limit: 128m
    ulimits:
      nofile: 4096
    # If you want coturn to listen on the host’s external IP only:
    # networks:
    #   default:
    #     ipv4_address: YOUR_VPS_IP

  proxy:
    image: nginx:stable-alpine
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ${LETSENCRYPT_PATH}:/etc/nginx/certs:ro
    mem_limit: 128m
    ulimits:
      nofile: 4096
    depends_on:
      - websocket
      - janus
      - coturn
