events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;

    upstream janus_http_backend {
        server janus:7088;
    }

    server {
        listen 443 ssl default_server;
        listen [::]:443 ssl default_server;
        
        server_name _;

        ssl_certificate     /etc/ssl_sink/certs/sink/fullchain.pem;
        ssl_certificate_key /etc/ssl_sink/certs/sink/privkey.pem;
        return 444;
    }
    
    server {
        listen 80 default_server;
        server_name _;
        return 444;
    }
    
    server {
        listen 80;
        listen [::]:80;

        server_name ${ENDPOINT};

        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        listen [::]:443 ssl;

        server_name ${ENDPOINT};

        ssl_certificate     /etc/nginx/certs/live/${ENDPOINT}/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/live/${ENDPOINT}/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_session_timeout 1d;
        ssl_session_cache shared:SSL:10m;

        # -----------------------------------------------------------------
        # 3️⃣ Serve the static front‑end (no proxy)
        # -----------------------------------------------------------------
        root   /usr/share/nginx/html;      # default for nginx:stable-alpine
        index  index.html index.htm;


        # Janus base endpoint
        location = /janus {
            proxy_pass http://janus_http_backend;

            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_read_timeout 120s;
            proxy_send_timeout 120s;
        }

        # Janus sessions and plugin requests
        location ^~ /janus/ {
            proxy_pass http://janus_http_backend;

            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_read_timeout 120s;
            proxy_send_timeout 120s;
        }
        location /ws/janus {
            proxy_pass http://janus:8188; 
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}

