listening-port=3478
listening-ip=0.0.0.0
external-ip=${EXTERNAL_IP}
# Bind to all interfaces inside container
lt-cred-mech

fingerprint
lt-cred-mech

realm=${ENDPOINT}
server-name=${ENDPOINT}

min-port=49152
max-port=65535

no-cli
